name: CI - Test find_lowest_number.py

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Tests
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt output1.txt
        python3 find_lowest_number.py test_data/test2_input.txt output2.txt
        python3 find_lowest_number.py test_data/test3_input.txt output3.txt

        diff output1.txt test_data/test1_expected.txt
        diff output2.txt test_data/test2_expected.txt
        diff output3.txt test_data/test3_expected.txt
